dependencies:
  - smartcontractkit/chainlink-brownie-contracts@0.4.0
  - OpenZeppelin/openzeppelin-contracts-upgradeable@4.5.0
  - OpenZeppelin/openzeppelin-contracts@4.5.0
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.4.0'
      - '@openzeppelin=OpenZeppelin'
dotenv: .env
networks:
  default: development
  # https://docs.chain.link/docs/vrf-contracts/
  mainnet:
    verify: True
  rinkeby:
    verify: True
wallets:
  from_key: ${PRIVATE_KEY}