dependencies:
  - smartcontractkit/chainlink-brownie-contracts@0.4.2
  - OpenZeppelin/openzeppelin-contracts-upgradeable@4.5.0
  - OpenZeppelin/openzeppelin-contracts@4.5.0
compiler:
  solc:
    optimizer:
      enabled: True
      runs: 1000000
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.4.2'
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.5.0'
      - '@openzeppelinUpgradeable=OpenZeppelin/openzeppelin-contracts-upgradeable@4.5.0'
dotenv: .env
networks:
  default: development
  mainnet:
    verify: True
  rinkeby:
    verify: True
  development:
    base_fee: 250000000000000000 # it's the premium. it costs 0.25 LINK per request.
    gas_price_link: 1000000000 # calculated value based on the gas price of the chain | LINK pre gas
    vrf_sub_fund_amount: 10000000000000000000 # 10 LINK
    key_hash: "0xd89b2bf150e3b9e13446986e571fb9cab24b13cea0a43ea20a6049a85cc807cc"
    call_back_gas_limit: 500000
wallets:
  from_key: ${PRIVATE_KEY}
